name: Run Component Tests

on:
  push: 
    branches:
    - "*"
  pull_request:
    branches: [ main ]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: run unit tests
      run: ./batect run-unit-tests
    
    - name: run sql tests
      run: ./batect run-sql-tests
    
    - name: run dynamodb tests
      run: ./batect run-dynamo-db-tests

    - name: run component tests
      run: ./batect run-component-tests