name: Run Component Tests

on:
  push: 
    branches:
    - "*"
  pull_request:
    branches: [ main ]

jobs:
  unit-test: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: run unit tests
      run: ./batect run-unit-tests
  
  sql-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: run sql tests
      run: ./batect run-sql-tests
    
  # dynamodb-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: checkout code
  #     uses: actions/checkout@v2
  #   - name: run dynamodb tests
  #     run: ./batect run-dynamo-db-tests
 

  component-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: run component tests
      run: ./batect run-component-tests